- CODEOWNERS
> [SELC-300] Remove marve from code owners

- .devops/deploy-pipelines.yml
- helm/templates/deployment.yaml
- helm/values-prod.yaml
- helm/values.yaml
Pulled a label to restart pods at each deploy + always pull image on PROD with TODO
> Devops 2.0 helm

- helm/templates/deployment.yaml
Co-authored-by: anttorre <antonio.torre@everis.com>
> jwt configured (#44)

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/product/connector/model/ProductOperations.java
- connector-api/src/test/java/it/pagopa/selfcare/product/connector/model/DummyProduct.java
- connector/dao/src/main/java/it/pagopa/selfcare/product/connector/dao/model/ProductEntity.java
- core/src/main/java/it/pagopa/selfcare/product/core/ProductServiceImpl.java
- core/src/main/resources/config/core-config.properties
- core/src/test/java/it/pagopa/selfcare/product/core/ProductLogoImageServiceImplTest.java
- core/src/test/java/it/pagopa/selfcare/product/core/ProductServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/product/web/model/ProductDto.java
- web/src/main/java/it/pagopa/selfcare/product/web/model/ProductResource.java
- web/src/main/java/it/pagopa/selfcare/product/web/model/UpdateProductDto.java
- web/src/main/java/it/pagopa/selfcare/product/web/model/mapper/ProductMapper.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/product/web/controller/ProductControllerTest.java
- web/src/test/java/it/pagopa/selfcare/product/web/model/ProductResourceTest.java
- web/src/test/java/it/pagopa/selfcare/product/web/model/UpdateProductDtoTest.java
> add configuration to accept svg as logo

- app/src/main/resources/config/application.yml
- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/product/connector/model/BackOfficeConfigurations.java
- connector-api/src/main/java/it/pagopa/selfcare/product/connector/model/ProductOperations.java
- connector-api/src/test/java/it/pagopa/selfcare/product/connector/model/DummyBackOfficeConfigurations.java
- connector-api/src/test/java/it/pagopa/selfcare/product/connector/model/DummyProduct.java
- connector/dao/src/main/java/it/pagopa/selfcare/product/connector/dao/model/ProductEntity.java
- core/src/main/java/it/pagopa/selfcare/product/core/ProductServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/product/core/ProductServiceImplTest.java
- pom.xml
- web/src/main/java/it/pagopa/selfcare/product/web/model/BackOfficeConfigurationsResource.java
- web/src/main/java/it/pagopa/selfcare/product/web/model/ProductDto.java
- web/src/main/java/it/pagopa/selfcare/product/web/model/ProductResource.java
- web/src/main/java/it/pagopa/selfcare/product/web/model/UpdateProductDto.java
- web/src/main/java/it/pagopa/selfcare/product/web/model/mapper/ProductMapper.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/test/java/it/pagopa/selfcare/product/web/controller/ProductControllerTest.java
- web/src/test/java/it/pagopa/selfcare/product/web/model/BackOfficeConfigurationsResourceTest.java
- web/src/test/java/it/pagopa/selfcare/product/web/model/CreateProductDtoTest.java
- web/src/test/java/it/pagopa/selfcare/product/web/model/UpdateProductDtoTest.java
- web/src/test/java/it/pagopa/selfcare/product/web/model/mapper/ProductMapperTest.java
* add backoffice environment configurations
* make backOfficeEnvironmentConfigurations field optional
> add backoffice environment configurations (#73)

- connector/dao/src/main/java/it/pagopa/selfcare/product/connector/dao/ProductConnectorImpl.java
- connector/dao/src/test/java/it/pagopa/selfcare/product/connector/dao/ProductConnectorImplTest.java
Fix query to delete product (removed "enabled" criteria and added "status" criteria)
> Fix delete product

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/product/web/model/ContractResource.java
- web/src/main/java/it/pagopa/selfcare/product/web/model/ProductResource.java
Removed validation constraints on resources. 
It's not necessary to have validation on resource given in response. Validation checks are available only for incoming objects.
I have started microservice in local aiming dev environment, I have added a new product with missing fields into mongodb collection and retrieved this document with specific api. No error was returned.
> Removed validation constraints on resources

- README.md
> Add Status badge

- helm/pnpg/values-prod.yaml
- helm/pnpg/values.yaml
> Adding new pod label

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/product/connector/model/ProductOperations.java
- connector-api/src/test/java/it/pagopa/selfcare/product/connector/model/DummyProduct.java
- connector/dao/src/main/java/it/pagopa/selfcare/product/connector/dao/model/ProductEntity.java
- core/src/main/java/it/pagopa/selfcare/product/core/ProductService.java
- core/src/main/java/it/pagopa/selfcare/product/core/ProductServiceImpl.java
- core/src/test/java/it/pagopa/selfcare/product/core/ProductServiceImplTest.java
- web/src/main/java/it/pagopa/selfcare/product/web/controller/ProductController.java
- web/src/main/java/it/pagopa/selfcare/product/web/model/ProductDto.java
- web/src/main/java/it/pagopa/selfcare/product/web/model/ProductResource.java
- web/src/test/java/it/pagopa/selfcare/product/web/controller/ProductControllerTest.java
feat: added new api to verify if product is valid or not
> [SELC - 3049] added new api to verify if product is valid or not (#109)

- app/src/main/resources/swagger/api-docs.json
- pom.xml
> feat: updated common version

- app/src/main/resources/swagger/api-docs.json
- pom.xml
> feat: updated common version (#118)

- .devops/code-review-pipelines.yml
- .devops/deploy-pipelines.yml
- .devops/pnpg-code-review-pipelines.yml
- .devops/pnpg-deploy-pipelines.yml
- .github/workflows/release_open_api.yml
- Dockerfile
- connector/azure-storage/src/test/java/it/pagopa/selfcare/product/connector/azure_storage/AzureBlobClientTest.java
- pom.xml
- updated starter-parent version from 0.0.2 to 0.0.3 for jdk 17 update
- updated pipelines from 1.11 to 1.17
- updated dockerfile image
These updates are necessary as there is a need to upgrade to java 17
- Build was done locally
- the microservice was started locally and some APIs were invoked
> feat: updated pipelines version, starter parent version and Dockerfile

- app/src/main/resources/swagger/api-docs.json
- connector-api/src/main/java/it/pagopa/selfcare/product/connector/model/ProductOperations.java
- connector-api/src/test/java/it/pagopa/selfcare/product/connector/model/DummyProduct.java
- connector/dao/src/main/java/it/pagopa/selfcare/product/connector/dao/model/ProductEntity.java
- web/src/main/java/it/pagopa/selfcare/product/web/model/ProductDto.java
- web/src/main/java/it/pagopa/selfcare/product/web/model/ProductResource.java
- web/src/main/resources/swagger/swagger_en.properties
- web/src/main/resources/swagger/swagger_it.properties
- web/src/test/java/it/pagopa/selfcare/product/web/controller/ProductControllerTest.java
**List of Changes**
Added boolean "invoiceable" in every API outputs
**Motivation and Context**
For Billing Platform, We need to know wheter a product is invoiceable or not. This field provides this information
**How Has This Been Tested?**
Local environment.
> [SELC-3404] Feat: Added boolean "invoiceable" in API outputs

- helm/values-prod.yaml
Increase replicas to 2 in prod
Keeping a single replica is dangerous
> [SELC-3467] Increase replicas - PROD 

- .github/workflows/release_open_api.yml
Update step for check breaking changes into github action
Changed action to retrieve breaking changes into api-docs
> [SELC-3516] bug: update step for check breaking changes into github action

- app/src/main/resources/swagger/api-docs.json
- web/src/main/java/it/pagopa/selfcare/product/web/model/ProductResource.java
- web/src/test/java/it/pagopa/selfcare/product/web/model/ProductResourceTest.java
Added required constraints for resources in response
In order to give more details in API documentation, some constraint validations have been added into resource
> [SELC-3684] feat: added required constraints for resources in response

- web/src/main/java/it/pagopa/selfcare/product/web/model/ProductResource.java
…rned productResource entity
Removed validation on roleMappings and urlBo fields on the resource returned by product retrieval apis
Subproducts doesn't need rolemappings, since they inherit the parent product properties, this validation was unnecessary
> [SELC-3943] fix: validation error for missing rolemappings and urlBo on subproduct retrieve

- .github/workflows/opex_api.yml
- .identity/.terraform.lock.hcl
- .identity/03_github_environment.tf
- .identity/env/prod/backend.ini
- .identity/env/prod/backend.tfvars
- .identity/env/prod/terraform.tfvars
- .opex/api-selfcare-product/env/dev/config.yaml
- .opex/api-selfcare-product/env/prod/backend.ini
- .opex/api-selfcare-product/env/prod/backend.tfvars
- .opex/api-selfcare-product/env/prod/config.yaml
- .opex/api-selfcare-product/env/prod/terraform.tfvars
- api-spec/api-docs.json
- api-spec/api-pagopa-proxy.yaml
> Fix opex configuration

- infra/container_apps/env/dev-pnpg/terraform.tfvars
- infra/container_apps/env/dev/terraform.tfvars
- infra/container_apps/env/prod-pnpg/terraform.tfvars
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/main.tf
- infra/container_apps/variables.tf
> Workload profiles migration

- infra/container_apps/README.md
- infra/container_apps/env/uat-pnpg/terraform.tfvars
- infra/container_apps/env/uat/terraform.tfvars
- infra/container_apps/locals.tf
- infra/container_apps/main.tf
- infra/container_apps/variables.tf
Using terraform ca module with suffix
Migration uat env with -001 suffix
> chore: Migration uat using terraform ca module with suffix
